apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    tier: front
  name: vote-staging
spec:
  replicas: 1
  template:
    spec:
      containers:
      - image: schoolofdevops/vote:v3
        name: vote-staging
