apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base

replicas:
- count: 2
  name: vote
patches:
- path: deployment.yaml
- path: service.yaml

images:
- name: schoolofdevops/vote
  newName: schoolofdevops/vote
  newTag: v6

namespace: instavote


commonAnnotations:
  supported-by: habibul@ericsson.com
labels:
- includeSelectors: true
  pairs:
    env: staging
    project: instavote

configMapGenerator:
  - name: vote-options
    env: options.env
