apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base

patches:
- path: deployment.yaml
- path: service.yaml

replicas:
  - name: vote
    count: 7

images:
  - name: habibul786/vote
<<<<<<< HEAD
    newTag: v8 # {"$imagepolicy": "flux-system:vote-policy:tag"}
=======
    newTag: main-9332ae50-1724853974 # {"$imagepolicy": "flux-system:vote-policy:tag"}
>>>>>>> 9ec92e2ff2248ed264f33d53c66dea09914d4f2a

namespace: instavote

commonLabels:
  project: instavote
  env: staging

commonAnnotations:
  supported-by: habibulofc@gmail.com



