apiVersion: v1
kind: Service
metadata:
  name: vote-staging
spec:
  ports:
  - name: "80"
    nodePort: 30300
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: vote-staging
  type: NodePort
