apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: worker
    tier: front
  name: worker
spec:
  replicas: 5
  template:
    spec:
      $setElementOrder/containers:
      - name: worker
      containers:
      - image: schoolofdevops/worker:v3
        name: worker
