apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: vote
    tier: front
  name: vote
spec:
  replicas: 6
  template:
    spec:
      $setElementOrder/containers:
      - name: vote
      containers:
      - image: schoolofdevops/vote:v4
        name: vote
