apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: worker
    tier: front
  name: worker
spec:
  ports:
  - name: "80"
    nodePort: 32300
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: worker
  type: NodePort
